# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Meals and Entertainment', 'Meals and Entertainment'), ('Computer - Hardware', 'Computer - Hardware'), ('Computer - Software', 'Computer - Software'), ('Office Supplies', 'Office Supplies')], max_length=100)),
                ('expense_desc', models.CharField(max_length=200)),
                ('pre_tax_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
    ]
